### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by WoollenPanda275** [jasonwynn10/Pen#6]
![image](https://user-images.githubusercontent.com/65177508/86617233-db23e980-bfae-11ea-958a-9203ad78ec78.png)

**Comment by WoollenPanda275** [comment]
I havent changed anything. Just downloaded and reloaded then the error popped up please help when you can thanks

**Comment by jasonw4331** [comment]
weird, your file permissions dont let pocketmine read any plugin data files 🤔

**Comment by WoollenPanda275** [comment]
Do you know any ways on how to fix that?

**Comment by jasonw4331** [comment]
delete the pen data folder and try again

**Comment by WoollenPanda275** [comment]
ah the mcpack file wasnt loaded correctly. thanks for the help :)
